import "@/css/globals.css";
import { Poppins } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

import Logo from "@/assets/logo.svg";

const poppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppinsFont.className}>
        <header>
          <Link href="/">
            <Image
              src={Logo}
              alt="Logo.svg"
              fill={false}
            />
          </Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
